### ISSUE TITLE
About birds

### ISSUE THREAD

**Issue by jzarca01** [f3d0r/aspace-bike-feeds#1]
Hi,

Just to let you know that if you need, you can use this library i created a couple months ago [node-bird](https://www.github.com/jzarca01/node-bird)

**Comment by f3d0r** [comment]
Hi Jérémie! We actually tried out your library back in Sep/Oct, but faced some compatibility issues with other tools we used, I can't really recall specifically. But, thanks for the note, node-bird was awesome! :)
